# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FashionEye' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FashionEye
  
  pod 'UIKitSwiftDSL', '~> 1.0'
  pod 'Anchorage', '~> 4.5'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'AlamofireImage', '~> 4.1'
  pod 'Alamofire'
  pod 'RealmSwift'
  
end
